name: Sync PR to Notion

on:
  workflow_call:
    secrets:
      NOTION_TOKEN:
        required: true
      NOTION_DATABASE_ID:
        required: true

jobs:
  sync-notion:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22.17.1

      - uses: pnpm/action-setup@v2
        with:
          version: 10.13.1
          run_install: true

      - run: pnpm exec tsx scripts/sync-notion.ts
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
